In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [ ]:
data = pd.read_csv("data.csv")

In [ ]:
data.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [ ]:
data = data.drop(['date','street','city','statezip','country'],axis=1)


In [ ]:
x = data.iloc[:,1:-1].values
y = data.iloc[:,0].values

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

a=StandardScaler()

x=a.fit_transform(x)


In [ ]:
print(x)
print(y)

[[-0.44 -0.84 -0.83 ... -0.57 -0.67 -0.53]
 [ 1.76  0.43  1.57 ...  1.79 -0.07 -1.67]
 [-0.44 -0.21 -0.22 ...  0.12 -0.67 -0.16]
 ...
 [-0.44  0.43  0.9  ...  1.37 -0.67  1.29]
 [ 0.66 -0.21 -0.05 ... -0.88  1.53  0.11]
 [-0.44  0.43 -0.67 ... -0.39 -0.67  0.65]]
[ 313000.   2384000.    342000.   ...  416904.17  203400.    220600.  ]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred = regression.predict(x_test)
print(y_pred.shape)

(920,)


In [ ]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(-1,1), y_test.reshape(-1,1)),1))


[[512757.65 289000.  ]
 [622992.51 429900.  ]
 [249798.52 129000.  ]
 ...
 [370777.77  83300.  ]
 [406894.04 520000.  ]
 [238252.89 215000.  ]]


In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.5486776043155681