In [78]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [79]:
data = pd.read_csv("WineQT.csv")

In [80]:
print(data)
data.isnull().sum()

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [81]:
x=data.drop('quality',axis=1).values
y=data['quality'].values
print(type(x))

<class 'numpy.ndarray'>


In [82]:
print(x)


[[7.400e+00 7.000e-01 0.000e+00 ... 5.600e-01 9.400e+00 0.000e+00]
 [7.800e+00 8.800e-01 0.000e+00 ... 6.800e-01 9.800e+00 1.000e+00]
 [7.800e+00 7.600e-01 4.000e-02 ... 6.500e-01 9.800e+00 2.000e+00]
 ...
 [6.200e+00 6.000e-01 8.000e-02 ... 5.800e-01 1.050e+01 1.594e+03]
 [5.900e+00 5.500e-01 1.000e-01 ... 7.600e-01 1.120e+01 1.595e+03]
 [5.900e+00 6.450e-01 1.200e-01 ... 7.100e-01 1.020e+01 1.597e+03]]


In [83]:
print(y)

[5 5 5 ... 5 6 5]


In [84]:
y.shape

(1143,)

In [97]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)


In [98]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [99]:
print(y_train)

[2 3 4 2 3 3 3 3 2 2 3 4 2 3 3 3 2 3 2 4 2 3 4 2 2 3 3 2 3 3 2 2 3 2 3 3 3
 2 2 2 3 3 2 3 2 3 2 4 2 4 3 3 2 3 2 4 2 3 2 3 2 2 2 2 2 3 0 2 2 3 2 2 2 3
 3 2 3 2 4 2 2 2 3 4 3 2 2 3 3 3 2 1 2 2 2 3 3 2 2 4 4 1 2 4 3 3 2 3 4 3 2
 5 3 4 4 3 4 2 4 2 2 3 4 2 2 4 3 5 2 4 3 2 2 2 3 2 3 2 2 3 3 2 3 2 2 4 3 2
 5 2 3 3 2 4 2 2 3 2 3 2 3 4 3 3 2 3 4 3 2 2 2 2 2 3 3 3 2 2 2 3 2 2 3 3 2
 3 3 2 4 3 2 2 1 4 2 2 4 3 3 2 2 3 1 2 5 2 2 3 3 2 3 1 4 5 4 3 1 4 3 3 4 3
 3 3 2 4 5 3 3 3 3 2 3 4 2 3 2 3 2 4 3 3 3 2 3 3 2 2 3 3 2 3 2 2 3 3 2 4 2
 2 2 2 2 2 2 3 2 4 3 2 2 2 4 2 2 5 3 2 3 2 4 2 3 3 2 2 3 4 3 2 3 3 2 2 2 3
 3 2 3 4 3 3 2 2 2 3 3 2 2 2 2 2 1 2 3 3 2 3 2 4 2 4 3 2 2 2 4 2 2 2 4 2 2
 3 3 3 2 2 2 3 2 2 3 3 2 3 3 4 3 2 3 4 3 3 4 2 5 4 2 3 3 2 1 3 2 2 3 2 2 4
 3 3 3 2 3 0 2 3 2 2 3 3 2 2 4 2 2 2 3 2 2 3 3 2 3 3 2 1 4 2 4 3 2 3 3 2 1
 3 4 2 4 4 2 3 2 3 3 3 2 3 3 4 4 3 2 4 3 4 2 2 3 2 4 3 2 2 3 4 3 3 3 3 2 3
 3 2 2 3 3 3 3 2 3 1 2 4 3 3 3 4 3 3 4 3 2 4 3 3 3 2 2 3 2 2 3 2 2 5 3 2 4
 3 3 2 2 3 4 3 1 3 3 4 2 

In [119]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(x_train,y_train)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [120]:
classifier.fit(X = x_train,y=y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [121]:
y_pred = classifier.predict(x_test)

In [122]:
np.printoptions(precision=2)
print(np.concatenate((y_pred.reshape(-1,1),y_test.reshape(-1,1)),1))

[[2 2]
 [3 1]
 [2 3]
 [3 3]
 [2 2]
 [3 3]
 [3 2]
 [3 3]
 [3 3]
 [3 4]
 [2 2]
 [2 3]
 [2 3]
 [2 2]
 [3 3]
 [2 3]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [4 3]
 [2 2]
 [2 4]
 [3 3]
 [2 2]
 [3 2]
 [2 2]
 [3 3]
 [3 3]
 [3 2]
 [2 3]
 [2 2]
 [3 2]
 [3 3]
 [3 2]
 [3 3]
 [2 3]
 [3 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [3 5]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [3 2]
 [2 2]
 [2 2]
 [2 3]
 [2 3]
 [2 2]
 [3 3]
 [2 2]
 [2 3]
 [2 2]
 [3 3]
 [2 2]
 [3 2]
 [4 4]
 [2 2]
 [2 2]
 [3 3]
 [4 4]
 [3 3]
 [4 4]
 [2 3]
 [3 4]
 [3 2]
 [3 4]
 [2 2]
 [3 2]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [3 4]
 [3 3]
 [4 4]
 [2 1]
 [2 2]
 [2 3]
 [2 3]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 0]
 [3 2]
 [5 5]
 [2 2]
 [2 3]
 [3 3]
 [2 3]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 3]
 [2 3]
 [2 3]
 [3 3]
 [3 3]
 [4 3]
 [2 2]
 [2 2]
 [3 2]
 [3 3]
 [4 3]
 [3 3]
 [3 3]
 [3 4]
 [2 2]
 [2 3]
 [4 4]
 [3 3]
 [2 3]
 [2 2]
 [3 3]
 [3 3]
 [2 2]
 [4 3]
 [2 3]
 [2 2]
 [3 2]
 [2 3]
 [3 3]

In [123]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[ 0  0  1  0  0  0]
 [ 0  0  3  4  0  0]
 [ 0  0 78 22  0  0]
 [ 0  0 25 60  7  0]
 [ 0  0  3  9 15  0]
 [ 0  0  0  1  0  1]]


In [124]:
print(accuracy_score(y_test, y_pred))


0.6724890829694323


In [125]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=10.
  warnings.warn(


Accuracy: 61.72 %
Standard Deviation: 4.34 %


In [126]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(x_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=10.
  warnings.warn(


[12:13:25] WARNING: ../src/learner.cc:767: 
Parameters: { "C", "kernel" } are not used.

Best Accuracy: 62.92 %
Best Parameters: {'C': 0.25, 'gamma': 0.6, 'kernel': 'rbf'}
